services:
  postgres:
    image: postgres:15
    restart: always
    networks:
      - gym-network
    environment:
      POSTGRES_DB: gymapp
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U", "${DB_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - gym-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  config-server:
    build: ./config-server
    ports:
      - "8088:8088"
    networks:
      - gym-network
    depends_on:
      eureka-server:
        condition: service_healthy
    volumes:
      - ./config:/config
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  gateway-service:
    build: ./gateway-service
    ports:
      - "8050:8050"
    networks:
      - gym-network
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/

  user-service:
    build: ./user-service
    networks:
      - gym-network
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=postgres

  workout-generation-service:
    build: ./workout-generation-service
    networks:
      - gym-network
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=postgres

  auth-service:
    build: ./auth-service
    networks:
      - gym-network
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=postgres

  schedule-service:
    build: ./schedule-service
    networks:
      - gym-network
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=postgres

networks:
  gym-network:
    driver: bridge

volumes:
  pgdata: