openapi: 3.0.3
info:
  title: Workout Generation Service API
  version: 1.0.1
  description: API do zarządzania i generowania planów treningowych

paths:
  /:
    get:
      summary: Pobierz wszystkie workouty
      responses:
        '201':
          description: Lista wszystkich workoutów
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Workout'
    post:
      summary: Dodaj nowy workout
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Workout'
      responses:
        '201':
          description: Workout został utworzony
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workout'

  /{id}:
    get:
      summary: Pobierz workout po ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '201':
          description: Workout znaleziony
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workout'
        '404':
          description: Workout nie znaleziony
    delete:
      summary: Usuń workout po ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Workout usunięty
        '404':
          description: Workout nie znaleziony

  /exercises/wger:
    get:
      summary: Pobierz ćwiczenia z wger API
      responses:
        '200':
          description: Lista ćwiczeń
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exercise'

  /exercises/wger/filter:
    get:
      summary: Pobierz ćwiczenia z wger API filtrowane po grupach mięśniowych
      parameters:
        - in: query
          name: muscleGroups
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Lista ćwiczeń
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exercise'
        '400':
          description: Brak poprawnych grup mięśniowych

  /muscles:
    get:
      summary: Pobierz listę dostępnych grup mięśniowych
      responses:
        '200':
          description: Lista grup mięśniowych
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Muscles'

  /generate:
    post:
      summary: Wygeneruj workout na podstawie preferencji użytkownika
      parameters:
        - in: query
          name: targetArea
          required: false
          schema:
            type: string
            default: strength
        - in: query
          name: durationMinutes
          required: false
          schema:
            type: integer
            default: 60
        - in: query
          name: muscleGroups
          required: false
          schema:
            type: array
            items:
              type: string
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
        - in: header
          name: X-User-Id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Wygenerowany workout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workout'
        '503':
          description: Brak ćwiczeń do wygenerowania workoutu
        '500':
          description: Błąd serwera

components:
  schemas:
    Workout:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        exercises:
          type: array
          items:
            $ref: '#/components/schemas/Exercise'
        experienceLevel:
          type: string
        goal:
          type: string
    Exercise:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        sets:
          type: integer
        repetitions:
          type: integer
        weight:
          type: integer
        muscles:
          type: array
          items:
            $ref: '#/components/schemas/Muscles'
    Muscles:
      type: string
      description: Nazwa grupy mięśniowej