openapi: 3.1.1
info:
  title: User API
  description: API for managing user data
  version: 1.0.0

tags:
  - name: User
    description: Operations related to user management

paths:
  /info:
    get:
      summary: Get currently logged-in user info
      description: Retrieve information about a specific user (username, email, created date).
      tags:
        - User
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /users:
    get:
      summary: Get list of users
      description: Returns a list of users. Can be filtered by role.
      tags:
        - User
      parameters:
        - name: role
          in: query
          description: Filter users by role (e.g. member, coach)
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List of users returned
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /personalize:
    put:
      summary: Personalize user settings
      description: Update user preferences or personalization settings.
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                preferences:
                  type: object
                  description: Key-value pairs of user preferences
      responses:
        '200':
          description: Preferences updated successfully
        '400':
          description: Invalid input data
        '500':
          description: Internal server error
